name: Update package version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New package version'
        required: true
        default: ''
jobs:
  update_package_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn version --new-version ${{ github.event.inputs.version }}
